google_maps_api_key: your_google_maps_api_key
redis_connection_string: redis://redis:6379/0        # Or your Redis connection string
mongodb_connection_string: mongodb://mongodb:27017/  # Or your MongoDB connection string