services:
  # Event Mapper Service
  event-mapper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./config.yaml:/service/config.yaml:ro
    networks:
      - mts
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_started
    restart: unless-stopped

  # Redis Service
  redis:
   image: redis:latest
   ports:
     - published: 6379
       target: 6379
       protocol: tcp
   networks:
      - mts
   depends_on:
    - mongodb
    
  # MongoDB Service
  mongodb:
   image: mongo:latest
   ports:
     - published: 27017
       target: 27017
       protocol: tcp
   networks:
      - mts

networks:
  mts:
    driver: bridge